# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.URLField(default='www.non.com')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('member_phone', models.CharField(max_length=15)),
                ('member_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('member_mark', models.CharField(max_length=10)),
                ('member_auth', models.CharField(max_length=10)),
                ('member_saving', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orderlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.IntegerField()),
                ('orderdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('catalog_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Catalog')),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Savelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('tran_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.URLField()),
                ('telephone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('remark', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Shop'),
        ),
    ]
