# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='orderprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='orderremark',
            field=models.CharField(default='no', max_length=30),
        ),
    ]
