# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0002_auto_20170116_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_auth',
            field=models.CharField(default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_mark',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_saving',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='ordernum',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='orderremark',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='remark',
            field=models.CharField(max_length=15),
        ),
    ]
