# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0007_auto_20170123_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('description', models.CharField(max_length=100)),
                ('code', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('description', models.CharField(max_length=100)),
                ('code', models.SlugField(primary_key=True, serialize=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.VehicleBrand')),
            ],
        ),
        migrations.RenameField(
            model_name='beverage',
            old_name='telepone',
            new_name='telephone',
        ),
    ]
