# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0011_auto_20170131_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savelog',
            name='admin_name',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='bandongo.Member'),
        ),
    ]
