# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-02 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0014_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Category'),
        ),
    ]
