# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0015_auto_20170202_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='catalog_name',
            field=models.CharField(max_length=10),
        ),
    ]
