# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0017_schedule_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='drink',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='catalog_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Catalog'),
        ),
    ]
