# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0019_orderlog_schedule_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlog',
            name='schedule_time',
        ),
    ]
