# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0020_remove_orderlog_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='schedule_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bandongo.Schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='comment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default="1/22", max_length=15),
            preserve_default=False,
        ),
    ]
