# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0021_auto_20170203_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlog',
            name='schedule_name',
        ),
    ]
