# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0022_remove_orderlog_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='schedule_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bandongo.Schedule'),
            preserve_default=False,
        ),
    ]
