# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0024_auto_20170203_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='catalog_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Catalog'),
        ),
    ]
