# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-06 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0025_auto_20170205_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bag',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
