# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-06 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0026_category_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bag',
            field=models.IntegerField(),
        ),
    ]
