# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0027_auto_20170206_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='savelog',
            name='commemt',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
