# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0032_auto_20170208_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinking', models.CharField(max_length=10)),
                ('num', models.IntegerField(default=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.CharField(blank=True, max_length=10)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.CharField(blank=True, max_length=10)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Beverage',
            new_name='Drink',
        ),
        migrations.RenameModel(
            old_name='Shop',
            new_name='Food',
        ),
        migrations.RemoveField(
            model_name='orderlog',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='orderlog',
            name='schedule_name',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='brand',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='shop_name',
            new_name='foodShop',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_auth',
            new_name='auth',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_mark',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_saving',
            new_name='saving',
        ),
        migrations.RenameField(
            model_name='savelog',
            old_name='admin_name',
            new_name='adminName',
        ),
        migrations.RenameField(
            model_name='savelog',
            old_name='member_name',
            new_name='memberName',
        ),
        migrations.RenameField(
            model_name='savelog',
            old_name='tran_date',
            new_name='tranDate',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='beverage',
            new_name='drink',
        ),
        migrations.DeleteModel(
            name='Orderlog',
        ),
        migrations.DeleteModel(
            name='VehicleBrand',
        ),
        migrations.DeleteModel(
            name='VehicleModel',
        ),
        migrations.AddField(
            model_name='foodorder',
            name='foodName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Catalog'),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='memberName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Member'),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='scheduleName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Schedule'),
        ),
        migrations.AddField(
            model_name='drinkorder',
            name='memberName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Member'),
        ),
        migrations.AddField(
            model_name='drinkorder',
            name='scheduleName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Schedule'),
        ),
    ]
