# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0034_auto_20170209_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='pic',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='drink',
            name='pic',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='food',
            name='pic',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
