# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0035_auto_20170210_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='pic',
            field=models.ImageField(blank=True, upload_to='/static/pic/catalogPic/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='bag',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
