# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0035_auto_20170210_1520'),
        ('bandongo', '0036_auto_20170210_1656'),
    ]

    operations = [
    ]
