# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0038_auto_20170213_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='pic',
            field=models.ImageField(blank=True, upload_to='/static/pic/catalogPic/'),
        ),
    ]
