# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0040_auto_20170213_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='drinkorder',
            name='drinking',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='drinkorder',
            name='remark',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='remark',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
