# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0041_auto_20170213_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='pic',
            field=models.ImageField(blank=True, upload_to='static/pic/catalogPic/'),
        ),
    ]
