# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0042_auto_20170213_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='pic',
            field=models.ImageField(blank=True, upload_to='static/pic/food/'),
        ),
    ]
