# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0045_schedule_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
