# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0049_auto_20170227_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Drink')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Member')),
            ],
        ),
        migrations.CreateModel(
            name='WishFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Food')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandongo.Member')),
            ],
        ),
    ]
