# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0050_wishdrink_wishfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishdrink',
            name='realized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wishfood',
            name='realized',
            field=models.BooleanField(default=False),
        ),
    ]
