# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0051_auto_20170306_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='arrived',
            new_name='foodArrived',
        ),
        migrations.AddField(
            model_name='schedule',
            name='drinkArrived',
            field=models.BooleanField(default=False),
        ),
    ]
