# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandongo', '0053_member_lineid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lineId',
            new_name='lineid',
        ),
    ]
